#!/bin/sh

LIB_EXT="so"

if [[ "$OSTYPE" == "darwin"* ]]; then
  LIB_EXT="dylib"
fi

LIB_NAME="LLVMTesla.$LIB_EXT"

if [[ "$TESLA_BUILD_DIR" ]]; then
  LIB=`find $TESLA_BUILD_DIR/tesla -name $LIB_NAME`
else
  LIB="$LIB_NAME"
fi

opt -load "$LIB" -tesla-instrument "$@"
